### ISSUE TITLE
Kubernetes Plugin fails with NullPointerException when Pod name is set using generateName

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/kubernetes-elastic-agents#134]
When following elastic agent profile pod YAML is used:
```yaml
apiVersion: v1
kind: Pod
metadata:
  generateName: pod-name-prefix
  labels:
    app: web
spec:
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: gocd/gocd-agent-alpine-3.10:v19.7.0
```

The plugin fails to create a new elastic agent with the following error:
```
2019-09-05 14:06:39,917 ERROR [5705@MessageListener for CreateAgentListener] KubernetesPlugin:127 - Failed to handle request cd.go.elastic-agent.create-agent
java.lang.NullPointerException: null
	at cd.go.contrib.elasticagent.KubernetesInstanceFactory.setPodNameIfNecessary(KubernetesInstanceFactory.java:287)
	at cd.go.contrib.elasticagent.KubernetesInstanceFactory.createUsingPodYaml(KubernetesInstanceFactory.java:240)
	at cd.go.contrib.elasticagent.KubernetesInstanceFactory.create(KubernetesInstanceFactory.java:61)
	at cd.go.contrib.elasticagent.KubernetesAgentInstances.createKubernetesInstance(KubernetesAgentInstances.java:90)
	at cd.go.contrib.elasticagent.KubernetesAgentInstances.create(KubernetesAgentInstances.java:68)
	at cd.go.contrib.elasticagent.KubernetesAgentInstances.create(KubernetesAgentInstances.java:39)
	at cd.go.contrib.elasticagent.executors.CreateAgentRequestExecutor.execute(CreateAgentRequestExecutor.java:44)
	at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:82)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:152)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:149)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
	at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.createAgent(ElasticAgentExtensionV5.java:142)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:60)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:43)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:32)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:22)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:86)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:66)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by GaneshSPatil** [comment]
#### Possible Fix:
Add a validation error when elastic agent profile pod yaml contains `generateName` field

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/kubernetes-elastic-agents/pull/135
