### ISSUE TITLE
Elastic agents don't get assigned

### ISSUE THREAD

**Issue by maheshmadpathi** [gocd/kubernetes-elastic-agents#182]
##### Issue Type

- Bug Report

##### Summary

The elastic agents don't get created and previous agents don't get delete after deployment.

###### Basic environment details

* Go Version: `GoCD Version: 19.7.0 (9567-727ea9db824eb6971170ac2a886ff1072ff5a235).`
* JAVA Version: `12.0.1`
* OS: `Linux 4.14.123-111.109.amzn2.x86_64`
* Browser vendor and version (if relevant): `Chrome`

##### Steps to Reproduce

I'm not sure how to reproduce this issue, however trying a `sleep` for longer time may reproduce
1. Create a pipeline, with `sleep` for longer period
2. execute the pipeline in an elastic agent and let it run
3. see if the above said pipeline gets succeeded and agent deleted.
4. if the agent isn't delete then execute the pipeline again and see if new agents are created and auto assigned.

##### Expected Results

The Elastic agents are created assigned to pipelines to do the job.
##### Actual Results

Few previously run pipelines have left elastic agents behind, which I think is causing `GoCD Server` to not to create new agents and assign, I may be wrong.
After Restarting the server it works fine but it happens quite often.

One more thing I would like highlight is that `GoCD Server` Pod continues to run in behind however the ELB gives a  http 503 error, The ELB health check gets passed and `kubectl logs` have below errors, but after sometimes the service becomes available

```bash
jvm 1    | 2020-03-23 09:26:51,430 ERROR [Thread-81] DefaultPluginManager:154 - This is an invalid request type :go.plugin-settings.get-configuration
jvm 1    | 2020-03-23 09:26:52,154 ERROR [Thread-81] p.c.g.a.l.c.g.a.l.LdapPlugin:127 [plugin-cd.go.authentication.ldap] - Error while executing request go.plugin-settings.get-configuration
```

##### Possible Fix

Restart `GoCD Server` pod

**Comment by arvindsv** [comment]
I'm going to close this issue for now. Let's re-open it once it comes back and we have logs. Thanks!

**Comment by maheshmadpathi** [comment]
Hi @GaneshSPatil and @arvindsv 
I faced this issue again today, please see below logs.

```bash
kubectl get po -n gocd                                                                                                     
NAME                                              READY   STATUS    RESTARTS   AGE
gocd-app-server-86b4b5cf8-h8wnq                   1/1     Running   0          7d22h
spcp-devops7dc041f3-2c68-4834-8fdc-4d03dfe137ab   1/1     Running   0          66m
```
below is the log

```bash
jvm 1    | 2020-03-31 08:18:26,091 ERROR [156@MessageListener for CreateAgentListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:127 [plugin-cd.go.contrib.elasticagent.kubernetes] - Failed to handle request cd.go.elastic-agent.create-agent
jvm 1    | io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
jvm 1    | 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
jvm 1    | 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
jvm 1    | 	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
jvm 1    | 	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
jvm 1    | 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
jvm 1    | 	at cd.go.contrib.elasticagent.KubernetesAgentInstances.refreshAll(KubernetesAgentInstances.java:150)
jvm 1    | 	at cd.go.contrib.elasticagent.KubernetesPlugin.refreshInstancesForCluster(KubernetesPlugin.java:134)
jvm 1    | 	at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:82)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:152)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
```

```bash
jvm 1    | 2020-03-31 08:19:16,110 ERROR [110@MessageListener for WorkFinder] JMSMessageListenerAdapter:90 - Exception thrown in message handling by listener com.thoughtworks.go.server.messaging.scheduling.WorkFinder@258dc009
jvm 1    | java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed to handle request cd.go.elastic-agent.should-assign-work'
jvm 1    | 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:58)
jvm 1    | 	at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.shouldAssignWork(ElasticAgentExtensionV5.java:162)
jvm 1    | 	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.shouldAssignWork(ElasticAgentExtension.java:68)
jvm 1    | 	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.shouldAssignWork(ElasticAgentPluginRegistry.java:58)
jvm 1    | 	at com.thoughtworks.go.server.service.ElasticAgentPluginService.shouldAssignWork(ElasticAgentPluginService.java:240)
jvm 1    | 	at com.thoughtworks.go.server.service.BuildAssignmentService.findMatchingJob(BuildAssignmentService.java:200)
jvm 1    | 	at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:178)
jvm 1    | 	at com.thoughtworks.go.server.service.BuildAssignmentService.assignWorkToAgent(BuildAssignmentService.java:159)
jvm 1    | 	at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:59)
jvm 1    | 	at com.thoughtworks.go.server.messaging.scheduling.WorkFinder.onMessage(WorkFinder.java:32)
```

```bash
jvm 1    | 2020-03-31 07:17:27,080 ERROR [103@MessageListener for JobStatusListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:127 [plugin-cd.go.contrib.elasticagent.kubernetes] - Failed to handle request cd.go.elastic-agent.job-completion
jvm 1    | io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
jvm 1    |      at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
jvm 1    |      at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
jvm 1    |      at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
jvm 1    |      at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
jvm 1    |      at cd.go.contrib.elasticagent.KubernetesAgentInstances.refreshAll(KubernetesAgentInstances.java:150)
jvm 1    |      at cd.go.contrib.elasticagent.KubernetesPlugin.refreshInstancesForCluster(KubernetesPlugin.java:134)
jvm 1    |      at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:97)
jvm 1    |      at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:152)
jvm 1    |      at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
```
```bash
jvm 1    | 2020-03-31 07:17:59,168 ERROR [160@MessageListener for ServerPingListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:127 [plugin-cd.go.contrib.elasticagent.kubernetes] - Failed to handle request cd.go.elastic-agent.server-ping
jvm 1    | io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
jvm 1    |      at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
jvm 1    |      at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
jvm 1    |      at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:237)
jvm 1    |      at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
jvm 1    |      at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
jvm 1    |      at cd.go.contrib.elasticagent.KubernetesAgentInstances.refreshAll(KubernetesAgentInstances.java:150)
jvm 1    |      at cd.go.contrib.elasticagent.KubernetesPlugin.refreshInstancesForCluster(KubernetesPlugin.java:134)
jvm 1    |      at cd.go.contrib.elasticagent.KubernetesPlugin.refreshInstancesForAllClusters(KubernetesPlugin.java:124)
jvm 1    |      at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:92)
jvm 1    |      at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:152)
jvm 1    |      at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:303)
jvm 1    |      at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
jvm 1    |      at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:149)
jvm 1    |      at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
jvm 1    |      at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.serverPing(ElasticAgentExtensionV5.java:152)
jvm 1    |      at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.serverPing(ElasticAgentExtension.java:64)
jvm 1    |      at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.serverPing(ElasticAgentPluginRegistry.java:52)
jvm 1    |      at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:31)
jvm 1    |      at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:21)
jvm 1    |      at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:86)
jvm 1    |      at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:66)
jvm 1    |      at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | Caused by: java.net.SocketTimeoutException: timeout
```

**Comment by maheshmadpathi** [comment]
Can you please reopen the bug ?

**Comment by GaneshSPatil** [comment]
HI @maheshmadpathi - What version of the Kubernetes Elastic Agent Plugin you're using? You can find information about it from `/go/admin/plugins` page.

**Comment by maheshmadpathi** [comment]
Hi @GaneshSPatil 

```bash
Id:  cd.go.contrib.elasticagent.kubernetes
Description: Kubernetes Based Elastic Agent Plugins for GoCD
Author: ThoughtWorks, Inc.
Supported operating systems: No restrictions
Plugin file location: /go-working-dir/plugins/external/kubernetes-elastic-agents.jar
Bundled: No
Target GoCD Version: 19.3.0
```

**Comment by maheshmadpathi** [comment]
I notice a weird issue, When delete the `GoCD` server pod to restart the server, it comes up online and starts pipelines and agent pods gets started but not assigned to pipelines, and also after sometime the `GoCD` server shows `503 Service Temporarily Unavailable` but server pod keeps running.
```bash
$ kubectl get po -n gocd                                                                                                        [16:47:31]
NAME                                              READY   STATUS    RESTARTS   AGE
gocd-app-server-86b4b5cf8-sdj58                   1/1     Running   0          10m
```
but I can't query for logs only, so my connection to k8s API is fine logs aren't shown
```bash
$ kubectl logs -f gocd-app-server-86b4b5cf8-sdj58 -n gocd                                                                       [16:50:58]
^C
FAIL
```
but If I wait for 10 mins or so the service comes online on its own, very strange but any idea why it happens.

**Comment by GaneshSPatil** [comment]
> Hi @GaneshSPatil
> 
> ```shell
> Id:  cd.go.contrib.elasticagent.kubernetes
> Description: Kubernetes Based Elastic Agent Plugins for GoCD
> Author: ThoughtWorks, Inc.
> Supported operating systems: No restrictions
> Plugin file location: /go-working-dir/plugins/external/kubernetes-elastic-agents.jar
> Bundled: No
> Target GoCD Version: 19.3.0
> ```

Hi @maheshmadpathi 

This information does not contain the Plugin version. Next the plugin name the version is specified. Look at the following screen shot.

<img width="920" alt="Screen Shot 2020-03-31 at 2 36 20 PM" src="https://user-images.githubusercontent.com/15275847/78008335-2baafb80-735d-11ea-9d5c-0e3c378339c8.png">


Can you provide this information?

**Comment by maheshmadpathi** [comment]
Sorry
`Version:3.0.0-156`

**Comment by GaneshSPatil** [comment]
Thank you very much for the information.

It looks like you're facing issues mentioned https://github.com/gocd/kubernetes-elastic-agents/issues/131 and https://github.com/gocd/kubernetes-elastic-agents/issues/132

This issue has been fixed as part of [Kubernetes Elastic Agent Plugin Release v3.1.0-exp](https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v3.1.0-180-exp).

Can you please upgrade your plugin version to the latest [Kubernetes Elastic Agent Plugin Release v3.6.0-209](https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v3.6.0-209).

If this problem persist, we can re-open this issue and investigate further.
