### ISSUE TITLE
Long delay when creating new agents.

### ISSUE THREAD

**Issue by goeranu** [gocd/kubernetes-elastic-agents#197]
We have noticed a long delay when creating new agents.  Most of the time the job finishes eventually, but after a very long delay.

When looking at the logs of those jobs, we note GoCD attempts to create a new pod, but reports it fails after 10 seconds.  Then a couple of minutes later it tries again to create a new pod, which also fails, and the pattern repeats. See the beginning of an example log below.  After many attempts, it often succeeds in the end.

If we understand the code correctly, the timeout happens inside `io.fabric8.kubernetes.client.DefaultKubernetesClient` and there is a property `kubernetes.request.timeout` which seems it might affect this.  But since there is no provision to tune this directly from `kubernetes-elastic-agents` I'm hesitant to tweak that, fearing I'm breaking some assumptions elsewhere.

Is something else in our environment severely broken when it takes more than 10 seconds to complete this call?  Is setting the above property a good way to solve the problem?  Or what is a proper way to handle this issue?

    ##|08:29:05.293 [go] Received request to create a pod for job JobIdentifier{pipelineName='elastic-k8s-test', pipelineCounter=11, pipelineLabel='11', stageName='defaultStage', stageCounter='1', jobName='k8s-alpine', jobId=9,874,193} in cluster https://kubernetes.service.cloud.jeppesensystems.com:6443 at 2020-06-01 08:29:05 +02:00
    ##|08:29:15.377 [go] Waiting to create agent pod.
    ##|08:29:25.380 [go] Failed to create agent pod: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [gocd-prod]  failed.
    ##|08:31:05.388 [go] Received request to create a pod for job JobIdentifier{pipelineName='elastic-k8s-test', pipelineCounter=11, pipelineLabel='11', stageName='defaultStage', stageCounter='1', jobName='k8s-alpine', jobId=9,874,193} in cluster https://kubernetes.service.cloud.jeppesensystems.com:6443 at 2020-06-01 08:31:05 +02:00
    ##|08:31:05.397 [go] Waiting to create agent pod.
    ##|08:31:15.400 [go] Failed to create agent pod: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [gocd-prod]  failed.
    ##|08:33:05.482 [go] Received request to create a pod for job JobIdentifier{pipelineName='elastic-k8s-test', pipelineCounter=11, pipelineLabel='11', stageName='defaultStage', stageCounter='1', jobName='k8s-alpine', jobId=9,874,193} in cluster https://kubernetes.service.cloud.jeppesensystems.com:6443 at 2020-06-01 08:33:05 +02:00
    ##|08:33:05.503 [go] Waiting to create agent pod.
    ##|08:33:15.506 [go] Failed to create agent pod: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [gocd-prod]  failed.
    ##|08:35:05.627 [go] Received request to create a pod for job JobIdentifier{pipelineName='elastic-k8s-test', pipelineCounter=11, pipelineLabel='11', stageName='defaultStage', stageCounter='1', jobName='k8s-alpine', jobId=9,874,193} in cluster https://kubernetes.service.cloud.jeppesensystems.com:6443 at 2020-06-01 08:35:05 +02:00
    ##|08:35:45.846 [go] Waiting to create agent pod.
    ##|08:35:55.849 [go] Failed to create agent pod: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [gocd-prod]  failed.
    ##|08:37:09.465 [go] Received request to create a pod for job JobIdentifier{pipelineName='elastic-k8s-test', pipelineCounter=11, pipelineLabel='11', stageName='defaultStage', stageCounter='1', jobName='k8s-alpine', jobId=9,874,193} in cluster https://kubernetes.service.cloud.jeppesensystems.com:6443 at 2020-06-01 08:37:09 +02:00
    ##|08:37:09.475 [go] Waiting to create agent pod.
    ##|08:37:19.482 [go] Failed to create agent pod: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [gocd-prod]  failed.
    ##|08:39:09.557 [go] Received request to create a pod for job JobIdentifier{pipelineName='elastic-k8s-test', pipelineCounter=11, pipelineLabel='11', stageName='defaultStage', stageCounter='1', jobName='k8s-alpine', jobId=9,874,193} in cluster https://kubernetes.service.cloud.jeppesensystems.com:6443 at 2020-06-01 08:39:09 +02:00
    ##|08:39:37.928 [go] Waiting to create agent pod.
    ##|08:39:47.931 [go] Failed to create agent pod: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [gocd-prod]  failed.

**Comment by arvindsv** [comment]
Is there more information / a stack trace in the plugin logs?

**Comment by chrislovsund** [comment]
Yes, here it is.
```
2020-06-02 17:39:04,262 INFO  [201@MessageListener for CreateAgentListener] KubernetesPlugin:72 - [Create Agent] Creating K8s pod with spec: Pod(apiVersion=v1, kind=Pod, metadata=ObjectMeta(annotations={PodSpecType=properties, Privileged=, MaxCPU=2, Environment=, Elastic-Agent-Job-Identifier={"pipeline_name":"atrium-jct-verify-rpm-signatures-rhel7","pipeline_counter":2481,"pipeline_label":"4.4.4753","stage_name":"verify-rpms","stage_counter":"1","job_name":"verify-rpms","job_id":9879569}, Image=docker.service.cloud.jeppesensystems.com/gocd7centos, PodConfiguration=apiVersion: v1
kind: Pod
metadata:
  name: pod-name-prefix-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: {{ GOCD_AGENT_IMAGE }}:{{ LATEST_VERSION }}
      securityContext:
        privileged: true, SpecifiedUsingPodConfiguration=, RemoteFile=, MaxMemory=2048M, RemoteFileType=json}, clusterName=null, creationTimestamp=2020-06-02T15:39:04Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={Elastic-Agent-Created-By=cd.go.contrib.elasticagent.kubernetes, Elastic-Agent-Job-Id=9879569, kind=kubernetes-elastic-agent}, managedFields=[], name=k8s-ea-c04dedb1-c9df-4b05-8503-5ad46589d229, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, affinity=null, automountServiceAccountToken=null, containers=[Container(args=[], command=[], env=[EnvVar(name=GO_EA_SERVER_URL, value=https://gocd-server.got.jeppesensystems.com/go, valueFrom=null, additionalProperties={}), EnvVar(name=GO_EA_AUTO_REGISTER_KEY, value=0ca30a35-7607-4dcd-aa34-255cad31be9f, valueFrom=null, additionalProperties={}), EnvVar(name=GO_EA_AUTO_REGISTER_ELASTIC_AGENT_ID, value=k8s-ea-c04dedb1-c9df-4b05-8503-5ad46589d229, valueFrom=null, additionalProperties={}), EnvVar(name=GO_EA_AUTO_REGISTER_ELASTIC_PLUGIN_ID, value=cd.go.contrib.elasticagent.kubernetes, valueFrom=null, additionalProperties={})], envFrom=[], image=docker.service.cloud.jeppesensystems.com/gocd7centos:latest, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=null, name=k8s-ea-c04dedb1-c9df-4b05-8503-5ad46589d229, ports=[], readinessProbe=null, resources=ResourceRequirements(limits={memory=Quantity(amount=2147483648, format=null, additionalProperties={}), cpu=Quantity(amount=2, format=null, additionalProperties={})}, requests=null, additionalProperties={}), securityContext=SecurityContext(allowPrivilegeEscalation=null, capabilities=null, privileged=false, procMount=null, readOnlyRootFilesystem=null, runAsGroup=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, windowsOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeDevices=[], volumeMounts=[], workingDir=null, additionalProperties={})], dnsConfig=null, dnsPolicy=null, enableServiceLinks=null, hostAliases=[], hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], initContainers=[], nodeName=null, nodeSelector=null, preemptionPolicy=null, priority=null, priorityClassName=null, readinessGates=[], restartPolicy=null, runtimeClassName=null, schedulerName=null, securityContext=null, serviceAccount=null, serviceAccountName=null, shareProcessNamespace=null, subdomain=null, terminationGracePeriodSeconds=null, tolerations=[], volumes=[], additionalProperties={}), status=PodStatus(conditions=[], containerStatuses=[], hostIP=null, initContainerStatuses=[], message=null, nominatedNodeName=null, phase=null, podIP=null, qosClass=null, reason=null, startTime=null, additionalProperties={}), additionalProperties={}).
2020-06-02 17:39:14,264 ERROR [201@MessageListener for CreateAgentListener] KubernetesPlugin:127 - Failed to handle request cd.go.elastic-agent.create-agent
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [gocd-prod]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:331)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:324)
	at cd.go.contrib.elasticagent.KubernetesInstanceFactory.createKubernetesPod(KubernetesInstanceFactory.java:153)
	at cd.go.contrib.elasticagent.KubernetesInstanceFactory.createUsingProperties(KubernetesInstanceFactory.java:96)
	at cd.go.contrib.elasticagent.KubernetesInstanceFactory.create(KubernetesInstanceFactory.java:57)
	at cd.go.contrib.elasticagent.KubernetesAgentInstances.createKubernetesInstance(KubernetesAgentInstances.java:94)
	at cd.go.contrib.elasticagent.KubernetesAgentInstances.create(KubernetesAgentInstances.java:68)
	at cd.go.contrib.elasticagent.KubernetesAgentInstances.create(KubernetesAgentInstances.java:39)
	at cd.go.contrib.elasticagent.executors.CreateAgentRequestExecutor.execute(CreateAgentRequestExecutor.java:52)
	at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:82)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
	at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.createAgent(ElasticAgentExtensionV5.java:141)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.createAgent(ElasticAgentExtension.java:59)
	at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.createAgent(ElasticAgentPluginRegistry.java:42)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:31)
	at com.thoughtworks.go.server.messaging.elasticagents.CreateAgentListener.onMessage(CreateAgentListener.java:21)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:119)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:110)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:411)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:372)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:241)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:813)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:328)
	... 22 common frames omitted
2020-06-02 17:39:35,407 INFO  [205@MessageListener for ServerPingListener] KubernetesPlugin:72 - Recycling kubernetes client on timer...
2020-06-02 17:39:35,473 INFO  [205@MessageListener for ServerPingListener] KubernetesPlugin:72 - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 0.
2020-06-02 17:40:35,416 INFO  [205@MessageListener for ServerPingListener] KubernetesPlugin:72 - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 0.
```

**Comment by chrislovsund** [comment]
We should also mention that we have kubernetes version
```
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
And looking at https://github.com/fabric8io/kubernetes-client#compatibility-matrix it seems that k8s version is not supported by 
`compile group: 'io.fabric8', name: 'kubernetes-client', version: '4.6.0'`

**Comment by arvindsv** [comment]
The fact that the call eventually succeeds (does not timeout) seems to suggest that compatibility is not a problem. But, maybe it is worth trying an upgrade of the client to `4.10.2`? I (maybe naively) assume there no external API changes, and the upgrade is as simple as changing the version in build.gradle.

**Comment by chrislovsund** [comment]
I tried to upgrade to 4.9.2 (4.10.2) did not work for some reason, but I had the same problem anyway. 
I also tried to increase request timeout to 90 seconds, still the same issue.

**Comment by goeranu** [comment]
FWIW: We have continued to try to debug what is going on.  We have now realised the problem happens only when talking to one particular Kubernetes controller of the three.  Maybe something is wrong with our cluster, but it is still strange it only affects this plugin.  For example, oing `kubectl` calls works fine to any of the controllers.  But the plugin has severe problems to two of them.

**Comment by chrislovsund** [comment]
For some reason, it was related to [Vault Agent Sidecar Injector](https://www.vaultproject.io/docs/platform/k8s/injector#agent-sidecar-injector) that was running and giving these error messages. We still don't understand why, since other K8s pods and deployments seem to work fine. Does GoCD k8s plugin use vault injector somehow?

```
I0608 09:47:34.044946       1 trace.go:116] Trace[236514602]: "Create" url:/api/v1/namespaces/gocd-prod/pods,user-agent:okhttp/3.12.0,client:10.67.7.102 (started: 2020-06-08 09:47:24.044311684 +0000 UTC m=+1071835.967214055) (total time: 10.00061252s):
Trace[236514602]: [10.00061252s] [10.000449433s] END
I0608 09:47:44.093856       1 trace.go:116] Trace[409652273]: "Call mutating webhook" configuration:vault-agent-injector-cfg,webhook:vault.hashicorp.com,resource:/v1, Resource=pods,subresource:,operation:CREATE,UID:0a8e221e-74e4-4f5f-8575-21f14382f9ca (started: 2020-06-08 09:47:34.093887995 +0000 UTC m=+1071846.016790390) (total time: 9.999889589s):
Trace[409652273]: [9.999889589s] [9.999889589s] END
W0608 09:47:44.093909       1 dispatcher.go:168] Failed calling webhook, failing open vault.hashicorp.com: failed calling webhook "vault.hashicorp.com": Post https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=30s: context canceled
E0608 09:47:44.093926       1 dispatcher.go:169] failed calling webhook "vault.hashicorp.com": Post https://vault-agent-injector-svc.vault.svc:443/mutate?timeout=30s: context canceled
```

We disable the vault-agent-injector feature for now (we are not using it yet) and GoCD started working as before.

**Comment by arvindsv** [comment]
@chrislovsund No, not by itself as far as I know. The only thing related to GoCD which works with Vault is: https://github.com/gocd/gocd-vault-secret-plugin/

Not sure where the logs are from, but it looks like it's a webhook event configured somewhere.

**Comment by arvindsv** [comment]
I see, it's vault's way of trying to inject secrets directly into the pod. Seems like it affected the normal agent pod somehow? Thanks for responding with what you found. Maybe it'll help someone.

**Comment by chrislovsund** [comment]
> I see, it's vault's way of trying to inject secrets directly into the pod. Seems like it affected the normal agent pod somehow? Thanks for responding with what you found. Maybe it'll help someone.

Right, but it doesn't seem to cause any issue to any other Pods.

**Comment by arvindsv** [comment]
Hmm, yeah, weird. It says: `failing open vault.hashicorp.com`. Are these pods (or nodes they are on) more "locked down" than usual, from a network perspecive? Maybe external access is restricted at some level? From this plugin's perspective, all it knows is that it's asking for a pod to be created via API, given the pod configuration.

**Comment by chrislovsund** [comment]
Thanks for your help, we may look at this at a later time when we need to have sidecar injector enabled. The issue can be closed.
