### ISSUE TITLE
getting Could not parse certificate: java.io.IOException: Empty input

### ISSUE THREAD

**Issue by caljnj** [gocd/kubernetes-elastic-agents#266]
Hi 

i'm using the gocd helm chart version 1.38.0 and i'm getting the errors below. 

The really strange thing is that 

- it's creating the elastic container totally fine in my cluster (so it's obviously able to create the container)
- ServerPingListener is able to get a pod count (1)

but when it tries to list them then it fails with the error below. 

I've tried using all the gocd secrets that i can find in cluster. (default, gocd)

should i be creating my own service account with specific permissions for this plugin?

```    2021-10-06 12:58:59,649 ERROR [155@MessageListener for ServerPingListener] KubernetesPlugin:127 - Failed to handle request cd.go.elastic-agent.server-ping
    io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
            at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
            at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
            at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:187)
            at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:63)
            at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:51)
            at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init>(DefaultKubernetesClient.java:95)
            at cd.go.contrib.elasticagent.KubernetesClientFactory.createClientFor(KubernetesClientFactory.java:83)
            at cd.go.contrib.elasticagent.KubernetesClientFactory.client(KubernetesClientFactory.java:60)
            at cd.go.contrib.elasticagent.KubernetesAgentInstances.unregisteredAfterTimeout(KubernetesAgentInstances.java:201)
            at cd.go.contrib.elasticagent.KubernetesAgentInstances.terminateUnregisteredInstances(KubernetesAgentInstances.java:126)
            at cd.go.contrib.elasticagent.executors.ServerPingRequestExecutor.performCleanupForACluster(ServerPingRequestExecutor.java:63)
            at cd.go.contrib.elasticagent.executors.ServerPingRequestExecutor.execute(ServerPingRequestExecutor.java:48)
            at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:91)
            at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
            at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
            at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
            at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
            at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
            at com.thoughtworks.go.plugin.access.elastic.v5.ElasticAgentExtensionV5.serverPing(ElasticAgentExtensionV5.java:151)
            at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.serverPing(ElasticAgentExtension.java:63)
            at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.serverPing(ElasticAgentPluginRegistry.java:51)
            at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:31)
            at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:21)
            at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
            at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
            at java.base/java.lang.Thread.run(Unknown Source)
    Caused by: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
            at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(Unknown Source)
            at java.base/java.security.cert.CertificateFactory.generateCertificate(Unknown Source)
            at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:101)
            at io.fabric8.kubernetes.client.internal.CertUtils.createTrustStore(CertUtils.java:79)
            at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:115)
            at io.fabric8.kubernetes.client.internal.SSLUtils.trustManagers(SSLUtils.java:94)
            at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:82)
            ... 23 common frames omitted
    Caused by: java.io.IOException: Empty input
            ... 30 common frames omitted```

**Comment by brandonvin** [comment]
@caljnj How did you resolve this?

**Comment by chadlwilson** [comment]
My guess might be that the cluster CA cert is not there in (or has disappeared from) the elastic agent cluster profile. Might want to check the config there?
